### PR TITLE
Two fold commit for searchbar and app font 

### PR DESCRIPTION
**Pull request by finben**
This request is to work on the searchbar and the font throughout the app. 

**Search Bar**
A quick note on the search bar. It is very difficult to get it both rounded and shadowed. I spent all morning on that lol... So what I have now is somewhat a compromise it is slightly rounded with shadow. The problem is when you round out the search bar the shadow will still be a box shape. There is a method I tried to map the shadow around the search bar called UIBezier path but I couldn't get it working and some sources say it is heavy on system resources to custom draw a shadow.  I'm kind of at an impasse on getting it closer to spec for now. But let me know what you think of the search bar

**Font**
Make sure that the font works on your app. I put two font files in for MountSerrat but they look kind of wierd the way the uploaded through github so just make sure they come with the project when you get my branch. 

I found a way through view modifiers that the font will scale with accessibility changes. At this point I only have it working for UIText though and need to find a way for UISearchBar and UINavigationBar as well to scale. I think we can do it though and get the font that we want. 

TODO:  
 I have dynamic text working for body text but need to get it working for navigation text and searchbar. I will open an issue for this so we don't forget later.

### CODE REVIEW

**Comment by finben** [comment]
No worries, I wanted to learn how to do it anyways. I figured it was
probably unnecessary. San Francisco will be easier anyways and make the
code base easier to maintain.

**Comment by finben** [comment]
I'll do a different PR for just the search bar. Tomorrow I'm going to try and look at the verseStanzas again. I looked over your work a little bit and I'll see if I can implement it in.

**Comment by skywalkerdude** [comment]
Okay, that's fine. We tried our best haha.

Could you put it in a file named SearchBar instead of SearchBarModel and place it in the Common/UI Components folder? (I created the Common folder in #24 #

**Comment by finben** [comment]
Because it is now only a one file change and we already discussed approval to it I am just going to commit it into the navigation branch. Also, I needed to access the common folder on the branch anyways. Closing this down. The change will go in when we merge navigation branch to master.

**Pull request closed without merging**
