### PR TITLE
Core data is actually pretty easy to use... o.O

### PR DESCRIPTION
**Pull request by finben**
Main sources are 
https://www.youtube.com/watch?v=7_Afen3PlDE
https://www.youtube.com/watch?v=cuHzVt0VXJM

### CODE REVIEW

**Comment by skywalkerdude** [comment]
Are you still migrating everything to use Core Data? Are there significant benefits of Core Data vs Realm? I thought we looked at the videos and articles and chose Realm because it just becomes a file that we can inspect with the Realm inspector and that we can easily export and import if we need to do that. How come we are walking back that decision?

**Comment by finben** [comment]
@skywalkerdude I am kind of torn... Today, I started both actually lol. I tried to move everything to Realm first and when I got stuck there. I went to move everything to Core Data. 

I am not totally sure which is better. The benefit to core data is we aren't relying on a 3rd party library and I ended up actually finding it really easy to use. The Realm inspector is of no use anymore since we only got a 30 day free trial with it. So we can't even use that anymore. Realm may have some other benefits though. The amount of data we are going to be storing with either one is actually very small so I don't think it will matter to much in terms of performance. 

Whatever, you think is fine. I am fine with either. Just let me know what you think.

**Comment by skywalkerdude** [comment]
what did you get stuck with for realm?

**Comment by finben** [comment]
I was trying to register a TagStore and Xcode kept saying it could not cast it from TagStoreRealmImpl to TagStore protocol. But the other thing is I am not sure how the data will be structured. Right now we have a primary key on hymnIdentifier and we don't even store a field for favorite. We just add and delete objects and if they are in the db then they are favorites. With tags I am not sure the best way to do this. It's a many to many relationship I guess between tags and hymns. But then do I also treat favorites as its own field now?

**Comment by skywalkerdude** [comment]
> I was trying to register a TagStore and Xcode kept saying it could not cast it from TagStoreRealmImpl to TagStore protocol.
This sounds like a swift protocol problem, not a realm problem, right?

>  But the other thing is I am not sure how the data will be structured.
Here is the schema for the tags on Android:
```
{
  "formatVersion": 1,
  "database": {
    "version": 3,
    "identityHash": "72b84ee868ece7273f2d6a3a1e700be5",
    "entities": [
      {
        "tableName": "TAGS",
        "createSql": "CREATE TABLE IF NOT EXISTS `${TABLE_NAME}` (`HYMN_TYPE` TEXT NOT NULL, `HYMN_NUMBER` TEXT NOT NULL, `QUERY_PARAMS` TEXT NOT NULL, `TAG` TEXT NOT NULL, `SONG_TITLE` TEXT, PRIMARY KEY(`HYMN_TYPE`, `HYMN_NUMBER`, `QUERY_PARAMS`, `TAG`))",
        "fields": [
          {
            "fieldPath": "hymnType",
            "columnName": "HYMN_TYPE",
            "affinity": "TEXT",
            "notNull": true
          },
          {
            "fieldPath": "hymnNumber",
            "columnName": "HYMN_NUMBER",
            "affinity": "TEXT",
            "notNull": true
          },
          {
            "fieldPath": "queryParams",
            "columnName": "QUERY_PARAMS",
            "affinity": "TEXT",
            "notNull": true
          },
          {
            "fieldPath": "tag",
            "columnName": "TAG",
            "affinity": "TEXT",
            "notNull": true
          },
          {
            "fieldPath": "songTitle",
            "columnName": "SONG_TITLE",
            "affinity": "TEXT",
            "notNull": false
          }
        ],
        "primaryKey": {
          "columnNames": [
            "HYMN_TYPE",
            "HYMN_NUMBER",
            "QUERY_PARAMS",
            "TAG"
          ],
          "autoGenerate": false
        },
        "indices": [],
        "foreignKeys": []
      }
    ]
  }
}
```
Basically the schema is 5 fields: hymn type, hymn number, query params, tag, title with the first 4 fields as primary keys.

**Comment by finben** [comment]
Hmmm, yeah that makes sense. Can Favorites just be its own attribute as a Boolean? Seems like it would be easier that way?

**Comment by skywalkerdude** [comment]
I think that just takes up more space without giving much of a speed boost. Cuz now you have an extra column that every entry will need to have a value for. Writes will be slower because you have to write another field, and reads won't be faster because you still need to go through every entry anyway to find the entries with the favorites bit as true

**Pull request closed without merging**
